name: Build and publish image to Docker Hub

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build ./templates/ --tag cloud-native:$(date +%s)
        docker build -t cloud-native:$(date +%s) .
